"""add_ani_to_call

Revision ID: 05998adcc890
Revises: d7baab8cd2e3
Create Date: 2021-03-11 20:12:53.401292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05998adcc890'
down_revision = 'd7baab8cd2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('ani', sa.String(), nullable=True))
    op.create_index(op.f('ix_call_ani'), 'call', ['ani'], unique=False)
    op.execute('Update call set ani = cl.ani from call_leg cl where cl.call_id = call.id and cl.ani is not null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_ani'), table_name='call')
    op.drop_column('call', 'ani')
    # ### end Alembic commands ###
