"""add_queue_holiday_hours

Revision ID: 1629fe55beb6
Revises: 3b607d726b84
Create Date: 2021-05-19 18:51:52.816996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1629fe55beb6'
down_revision = '3b607d726b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_holiday', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('queue_holiday', sa.Column('start_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_holiday', 'start_time')
    op.drop_column('queue_holiday', 'end_time')
    # ### end Alembic commands ###
