"""update_workflow_fields

Revision ID: 36852e35df37
Revises: bc95403dd67c
Create Date: 2021-07-05 22:10:07.740244

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '36852e35df37'
down_revision = 'bc95403dd67c'
branch_labels = None
depends_on = None

partner_enum = postgresql.ENUM('IVR', 'ELOAN', 'TD', 'REGIONS', 'HSBC', 'PNC', 'BBVA', name='partner')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('workflow', sa.Column('partner', partner_enum, nullable=True))
    op.add_column('workflow_config', sa.Column('minimum_version', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_config', 'minimum_version')
    op.drop_column('workflow', 'partner')
    # ### end Alembic commands ###
