"""add_transfer_routing_to_call_leg

Revision ID: 3b607d726b84
Revises: 05998adcc890
Create Date: 2021-04-23 15:06:36.668079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b607d726b84'
down_revision = '05998adcc890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_leg', sa.Column('transfer_routing_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_call_leg_transfer_routing_id'), 'call_leg', ['transfer_routing_id'], unique=False)
    op.create_foreign_key(None, 'call_leg', 'transfer_routing', ['transfer_routing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_leg', type_='foreignkey')
    op.drop_index(op.f('ix_call_leg_transfer_routing_id'), table_name='call_leg')
    op.drop_column('call_leg', 'transfer_routing_id')
    # ### end Alembic commands ###
