"""add_queue_closed_message

Revision ID: 4b5aa50b91d4
Revises: 65e3d6e298c5
Create Date: 2021-09-10 03:26:57.759722

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4b5aa50b91d4'
down_revision = '65e3d6e298c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('closed_message', sa.String(), nullable=True))

    op.execute("UPDATE queue SET closed_message = '<break time=\"500ms\"/> We are currently closed. Please try us back during our normal business hours of 7am-10pm central time. We apologize for this inconvenience and look forward to speaking with you then.'")
    op.alter_column('queue', 'closed_message', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'closed_message')
    # ### end Alembic commands ###
