"""refactoring_indices

Revision ID: 634183f20e20
Revises: b85cfd32f0de
Create Date: 2021-09-03 17:52:52.879041

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '634183f20e20'
down_revision = 'b85cfd32f0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER INDEX ix_admin_call_call_routing_id RENAME TO ix_admin_call_inbound_routing_id')
    op.execute('ALTER INDEX ix_admin_call_telephony_system_id RENAME TO ix_admin_call_contact_system_id')
    op.drop_constraint('admin_call_call_routing_id_fkey', 'admin_call', type_='foreignkey')
    op.create_foreign_key(None, 'admin_call', 'inbound_routing', ['inbound_routing_id'], ['id'], ondelete='CASCADE')
    op.execute('ALTER INDEX ix_call_admin_call_id RENAME TO ix_contact_admin_call_id')
    op.execute('ALTER INDEX ix_call_ani RENAME TO ix_contact_device_identifier')
    op.execute('ALTER INDEX ix_call_global_id RENAME TO ix_contact_global_id')
    op.execute('ALTER INDEX ix_call_leg_ani RENAME TO ix_contact_leg_ani')
    op.execute('ALTER INDEX ix_call_leg_call_id RENAME TO ix_contact_leg_contact_id')
    op.execute('ALTER INDEX ix_call_leg_telephony_system_id RENAME TO ix_contact_leg_contact_system_id')
    op.execute('ALTER INDEX ix_call_leg_call_routing_id RENAME TO ix_contact_leg_inbound_routing_id')
    op.execute('ALTER INDEX ix_call_leg_initial_queue_id RENAME TO ix_contact_leg_initial_queue_id')
    op.execute('ALTER INDEX ix_call_leg_transfer_routing_id RENAME TO ix_contact_leg_transfer_routing_id')
    op.execute('ALTER INDEX ix_call_leg_workflow_run_id RENAME TO ix_contact_leg_workflow_run_id')
    op.execute('ALTER INDEX ix_call_routing_greeting_id RENAME TO ix_inbound_routing_greeting_id')
    op.execute('ALTER INDEX ix_call_routing_phone_number RENAME TO ix_inbound_routing_inbound_target')
    op.execute('ALTER INDEX ix_call_routing_initial_queue_id RENAME TO ix_inbound_routing_initial_queue_id')
    op.execute('ALTER INDEX ix_call_routing_workflow_id RENAME TO ix_inbound_routing_workflow_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER INDEX ix_contact_admin_call_id RENAME TO ix_call_admin_call_id')
    op.execute('ALTER INDEX ix_contact_device_identifier RENAME TO ix_call_ani')
    op.execute('ALTER INDEX ix_contact_global_id RENAME TO ix_call_global_id')
    op.execute('ALTER INDEX ix_contact_leg_ani RENAME TO ix_call_leg_ani')
    op.execute('ALTER INDEX ix_contact_leg_contact_id RENAME TO ix_call_leg_call_id')
    op.execute('ALTER INDEX ix_contact_leg_contact_system_id RENAME TO ix_call_leg_telephony_system_id')
    op.execute('ALTER INDEX ix_contact_leg_inbound_routing_id RENAME TO ix_call_leg_call_routing_id')
    op.execute('ALTER INDEX ix_contact_leg_initial_queue_id RENAME TO ix_call_leg_initial_queue_id')
    op.execute('ALTER INDEX ix_contact_leg_transfer_routing_id RENAME TO ix_call_leg_transfer_routing_id')
    op.execute('ALTER INDEX ix_contact_leg_workflow_run_id RENAME TO ix_call_leg_workflow_run_id')
    op.execute('ALTER INDEX ix_inbound_routing_greeting_id RENAME TO ix_call_routing_greeting_id')
    op.execute('ALTER INDEX ix_inbound_routing_inbound_target RENAME TO ix_call_routing_phone_number')
    op.execute('ALTER INDEX ix_inbound_routing_initial_queue_id RENAME TO ix_call_routing_initial_queue_id')
    op.execute('ALTER INDEX ix_inbound_routing_workflow_id RENAME TO ix_call_routing_workflow_id')
    op.drop_constraint(None, 'admin_call', type_='foreignkey')
    op.create_foreign_key('admin_call_call_routing_id_fkey', 'admin_call', 'inbound_routing', ['call_routing_id'], ['id'], ondelete='CASCADE')
    op.execute('ALTER INDEX ix_admin_call_inbound_routing_id RENAME TO  ix_admin_call_call_routing_id')
    op.execute('ALTER INDEX ix_admin_call_contact_system_id RENAME TO ix_admin_call_telephony_system_id')
    # ### end Alembic commands ###
