"""update_queue_transfer_layout

Revision ID: 65e3d6e298c5
Revises: d347719fb3a6
Create Date: 2021-07-13 02:32:07.302332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65e3d6e298c5'
down_revision = 'd347719fb3a6'
branch_labels = None
depends_on = None

productcode_enum = postgresql.ENUM('CREDIT_CARD', 'LOAN', name='productcode')
department_enum = postgresql.ENUM('CUSTOMERS', 'ORIGINATIONS', 'PAYMENTS', 'ANY', name='department')
contact_type_enum = postgresql.ENUM('IVR', 'SMS', 'CHAT', name='contacttype')
partner_enum = postgresql.ENUM('IVR', 'ELOAN', 'TD', 'REGIONS', 'HSBC', 'PNC', 'BBVA', name='partner')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('department', department_enum, nullable=True))
    op.add_column('queue', sa.Column('product', productcode_enum, nullable=True))
    op.add_column('queue', sa.Column('queue_contact_type', contact_type_enum, nullable=True))
    op.execute("UPDATE queue SET queue_contact_type = 'IVR'")
    op.alter_column('queue', 'queue_contact_type', existing_type=contact_type_enum, nullable=False)

    op.drop_column('transfer_routing', 'partner')
    op.drop_column('transfer_routing', 'product_code')
    op.drop_column('transfer_routing', 'department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_routing', sa.Column('partner', partner_enum, nullable=True))
    op.add_column('transfer_routing', sa.Column('product_code', productcode_enum, nullable=True))
    op.add_column('transfer_routing', sa.Column('department', department_enum, nullable=True))

    op.drop_column('queue', 'queue_contact_type')
    op.drop_column('queue', 'product')
    op.drop_column('queue', 'department')
    # ### end Alembic commands ###
