"""initial_migration

Revision ID: 930d0b79562f
Revises: 
Create Date: 2020-05-27 20:51:09.229543

"""

# revision identifiers, used by Alembic.
revision = '930d0b79562f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
