"""add_internal_transfer_enum

Revision ID: 9a2b4ec0fd71
Revises: d7baab8cd2e3
Create Date: 2021-04-16 02:15:58.582344

"""
from alembic import op
from sqlalchemy.dialects import postgresql

transfertype_enum = postgresql.ENUM('SIP', 'PSTN', 'INTERNAL', name='transfertype')


# revision identifiers, used by Alembic.
revision = '9a2b4ec0fd71'
down_revision = '1629fe55beb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    # Check the existing enum
    bind = op.get_bind()
    res = bind.execute("SELECT * from enum_range(null::transfertype)")
    if res:
        res = list(res.fetchall())
    # If the enum exists
    if res and len(res) > 0:
        enum_set = res[0][0]
        if "INTERNAL" not in enum_set:
            bind.execute("ALTER TYPE transfertype ADD VALUE 'INTERNAL'")
    else:
        transfertype_enum.create(bind=bind)
        # op.execute("ROLLBACK")
        # op.execute("CREATE TYPE transfertype AS ENUM ('SIP', 'PSTN', 'INTERNAL',)")
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
