"""add_branched_on_error

Revision ID: b85cfd32f0de
Revises: 65e3d6e298c5
Create Date: 2021-08-12 21:06:42.241937

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b85cfd32f0de'
down_revision = '4b5aa50b91d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_step_run', sa.Column('branched_on_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_step_run', 'branched_on_error')
    # ### end Alembic commands ###
