"""add_partner_to_queue

Revision ID: bc95403dd67c
Revises: f998f3404e11
Create Date: 2021-06-18 00:22:03.015442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'bc95403dd67c'
down_revision = 'f998f3404e11'
branch_labels = None
depends_on = None

partner_enum = postgresql.ENUM('IVR', 'ELOAN', 'TD', 'REGIONS', 'HSBC', 'PNC', 'BBVA', name='partner')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    # Check the existing enum
    bind = op.get_bind()
    res = bind.execute("SELECT * from enum_range(null::partner)")
    if res:
        res = list(res.fetchall())
    # If the enum exists
    if res and len(res) > 0:
        enum_set = res[0][0]
        if "BBVA" not in enum_set:
            bind.execute("ALTER TYPE partner ADD VALUE 'BBVA'")
    # If it doesnt exist this statement will create the enum
    op.add_column('queue', sa.Column('partner', partner_enum, nullable=True))
    # Update the current queue's to be pointed at Iivr (no partners are currently deployed)
    op.execute("UPDATE queue SET partner = 'IVR'")
    # Set this as a required field
    op.alter_column('queue', 'partner', existing_type=partner_enum, nullable=False)
    # ### end Alembic commands ###

    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'partner')
    # ### end Alembic commands ###
