"""update_transfer_types

Revision ID: c2753d4b4335
Revises: 6fb6ed5bba27
Create Date: 2021-01-26 01:50:21.348829

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c2753d4b4335'
down_revision = '6fb6ed5bba27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE transfertype ADD VALUE 'QUEUE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
