"""

Revision ID: c402912c0795
Revises: 832162cc2c97
Create Date: 2021-02-15 13:57:58.363085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c402912c0795'
down_revision = '832162cc2c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_call', sa.Column('workflow_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('scheduled_call', sa.Column('workflow_version_tag', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scheduled_call', 'workflow', ['workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_call', type_='foreignkey')
    op.drop_column('scheduled_call', 'workflow_version_tag')
    op.drop_column('scheduled_call', 'workflow_id')
    # ### end Alembic commands ###
