"""call_to_contact

Revision ID: d347719fb3a6
Revises: 36852e35df37
Create Date: 2021-07-06 00:32:18.328847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd347719fb3a6'
down_revision = '36852e35df37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    contacttype_enum = postgresql.ENUM('IVR', 'SMS', 'CHAT', name='contacttype')
    contacttype_enum.create(bind=op.get_bind())

    op.rename_table("call_routing", "inbound_routing")
    op.rename_table("call", "contact")
    op.rename_table("call_leg", "contact_leg")

    op.alter_column("contact", "ani", new_column_name="device_identifier")

    op.alter_column("contact_leg", "telephony_system", new_column_name="contact_system")
    op.alter_column("contact_leg", "telephony_system_id", new_column_name="contact_system_id")
    op.alter_column("contact_leg", "call_id", new_column_name="contact_id")
    op.alter_column("contact_leg", "call_routing_id", new_column_name="inbound_routing_id")

    op.alter_column("inbound_routing", "phone_number", new_column_name="inbound_target")

    op.alter_column("admin_call", "telephony_system", new_column_name="contact_system")
    op.alter_column("admin_call", "telephony_system_id", new_column_name="contact_system_id")
    op.alter_column("admin_call", "call_routing_id", new_column_name="inbound_routing_id")

    op.add_column('inbound_routing', sa.Column('contact_type', contacttype_enum, nullable=True))
    op.execute("UPDATE inbound_routing SET contact_type = 'IVR'")
    op.alter_column('inbound_routing', 'contact_type', nullable=False)

    op.add_column('contact', sa.Column('contact_type', contacttype_enum, nullable=True))
    op.execute("UPDATE contact SET contact_type = 'IVR'")
    op.alter_column('contact', 'contact_type', nullable=False)

    op.drop_column('inbound_routing', 'sip_trunk')

    op.add_column('contact', sa.Column('inbound_target', sa.String(), nullable=True))
    op.execute('Update contact set inbound_target = cl.dnis from contact_leg cl where cl.contact_id = contact.id and '
               'cl.dnis is not null')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'inbound_target')
    op.add_column('inbound_routing', sa.Column('sip_trunk', sa.String(), nullable=True))
    op.drop_column('contact', 'contact_type')
    op.drop_column('inbound_routing', 'contact_type')

    op.alter_column("admin_call", "inbound_routing_id", new_column_name="call_routing_id")
    op.alter_column("admin_call", "contact_system_id", new_column_name="telephony_system_id")
    op.alter_column("admin_call", "contact_system", new_column_name="telephony_system")

    op.alter_column("inbound_routing", "inbound_target", new_column_name="phone_number")
    op.alter_column("contact_leg", "inbound_routing_id", new_column_name="call_routing_id")
    op.alter_column("contact_leg", "contact_id", new_column_name="call_id")
    op.alter_column("contact_leg", "contact_system_id", new_column_name="telephony_system_id")
    op.alter_column("contact_leg", "contact_system", new_column_name="telephony_system")

    op.alter_column("contact", "device_identifier", new_column_name="ani")

    op.rename_table("contact_leg", "call_leg")
    op.rename_table("contact", "call")
    op.rename_table("inbound_routing", "call_routing")
    # ### end Alembic commands ###
