"""add_indexes

Revision ID: d7baab8cd2e3
Revises: 48fa985bfac4
Create Date: 2021-03-08 22:28:34.531584

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd7baab8cd2e3'
down_revision = '48fa985bfac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_call_call_routing_id'), 'admin_call', ['call_routing_id'], unique=False)
    op.create_index(op.f('ix_admin_call_user_id'), 'admin_call', ['user_id'], unique=False)
    op.create_index(op.f('ix_admin_phone_number_user_id'), 'admin_phone_number', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_credential_user_id'), 'api_credential', ['user_id'], unique=False)
    op.create_index(op.f('ix_call_admin_call_id'), 'call', ['admin_call_id'], unique=False)
    op.create_index(op.f('ix_call_leg_ani'), 'call_leg', ['ani'], unique=False)
    op.create_index(op.f('ix_call_leg_call_id'), 'call_leg', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_leg_call_routing_id'), 'call_leg', ['call_routing_id'], unique=False)
    op.create_index(op.f('ix_call_leg_initial_queue_id'), 'call_leg', ['initial_queue_id'], unique=False)
    op.create_index(op.f('ix_call_leg_workflow_run_id'), 'call_leg', ['workflow_run_id'], unique=False)
    op.create_index(op.f('ix_call_routing_greeting_id'), 'call_routing', ['greeting_id'], unique=False)
    op.create_index(op.f('ix_call_routing_initial_queue_id'), 'call_routing', ['initial_queue_id'], unique=False)
    op.create_index(op.f('ix_call_routing_workflow_id'), 'call_routing', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_queue_holiday_queue_id'), 'queue_holiday', ['queue_id'], unique=False)
    op.create_index(op.f('ix_queue_hours_of_operation_queue_id'), 'queue_hours_of_operation', ['queue_id'], unique=False)
    op.create_index(op.f('ix_scheduled_call_admin_call_id'), 'scheduled_call', ['admin_call_id'], unique=False)
    op.create_index(op.f('ix_scheduled_call_call_routing_id'), 'scheduled_call', ['call_routing_id'], unique=False)
    op.create_index(op.f('ix_scheduled_call_user_id'), 'scheduled_call', ['user_id'], unique=False)
    op.create_index(op.f('ix_scheduled_call_workflow_id'), 'scheduled_call', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_step_state_step_run_id'), 'step_state', ['step_run_id'], unique=False)
    op.create_index(op.f('ix_transfer_routing_queue_id'), 'transfer_routing', ['queue_id'], unique=False)
    op.create_index(op.f('ix_workflow_config_workflow_id'), 'workflow_config', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_current_queue_id'), 'workflow_run', ['current_queue_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_workflow_config_id'), 'workflow_run', ['workflow_config_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_workflow_id'), 'workflow_run', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_run_step_run_id'), 'workflow_step_run', ['step_run_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_run_step_state_id'), 'workflow_step_run', ['step_state_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_run_workflow_run_id'), 'workflow_step_run', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_step_run_workflow_run_id'), table_name='workflow_step_run')
    op.drop_index(op.f('ix_workflow_step_run_step_state_id'), table_name='workflow_step_run')
    op.drop_index(op.f('ix_workflow_step_run_step_run_id'), table_name='workflow_step_run')
    op.drop_index(op.f('ix_workflow_run_workflow_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_workflow_config_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_current_queue_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_config_workflow_id'), table_name='workflow_config')
    op.drop_index(op.f('ix_transfer_routing_queue_id'), table_name='transfer_routing')
    op.drop_index(op.f('ix_step_state_step_run_id'), table_name='step_state')
    op.drop_index(op.f('ix_scheduled_call_workflow_id'), table_name='scheduled_call')
    op.drop_index(op.f('ix_scheduled_call_user_id'), table_name='scheduled_call')
    op.drop_index(op.f('ix_scheduled_call_call_routing_id'), table_name='scheduled_call')
    op.drop_index(op.f('ix_scheduled_call_admin_call_id'), table_name='scheduled_call')
    op.drop_index(op.f('ix_queue_hours_of_operation_queue_id'), table_name='queue_hours_of_operation')
    op.drop_index(op.f('ix_queue_holiday_queue_id'), table_name='queue_holiday')
    op.drop_index(op.f('ix_call_routing_workflow_id'), table_name='call_routing')
    op.drop_index(op.f('ix_call_routing_initial_queue_id'), table_name='call_routing')
    op.drop_index(op.f('ix_call_routing_greeting_id'), table_name='call_routing')
    op.drop_index(op.f('ix_call_leg_workflow_run_id'), table_name='call_leg')
    op.drop_index(op.f('ix_call_leg_initial_queue_id'), table_name='call_leg')
    op.drop_index(op.f('ix_call_leg_call_routing_id'), table_name='call_leg')
    op.drop_index(op.f('ix_call_leg_call_id'), table_name='call_leg')
    op.drop_index(op.f('ix_call_leg_ani'), table_name='call_leg')
    op.drop_index(op.f('ix_call_admin_call_id'), table_name='call')
    op.drop_index(op.f('ix_api_credential_user_id'), table_name='api_credential')
    op.drop_index(op.f('ix_admin_phone_number_user_id'), table_name='admin_phone_number')
    op.drop_index(op.f('ix_admin_call_user_id'), table_name='admin_call')
    op.drop_index(op.f('ix_admin_call_call_routing_id'), table_name='admin_call')
    # ### end Alembic commands ###
