"""add_cascade_indexes

Revision ID: f4d22ae3bd91
Revises: 1827f4722bda
Create Date: 2021-01-19 20:51:52.903997

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f4d22ae3bd91'
down_revision = '1827f4722bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_call_call_routing_id_fkey', 'admin_call', type_='foreignkey')
    op.create_foreign_key('admin_call_call_routing_id_fkey', 'admin_call', 'call_routing', ['call_routing_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('call_leg_call_routing_id_fkey', 'call_leg', type_='foreignkey')
    op.drop_constraint('call_leg_call_id_fkey', 'call_leg', type_='foreignkey')
    op.create_foreign_key('call_leg_call_id_fkey', 'call_leg', 'call', ['call_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('call_leg_call_routing_id_fkey', 'call_leg', 'call_routing', ['call_routing_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('scheduled_call_call_routing_id_fkey', 'scheduled_call', type_='foreignkey')
    op.drop_constraint('scheduled_call_admin_call_id_fkey', 'scheduled_call', type_='foreignkey')
    op.create_foreign_key('scheduled_call_admin_call_id_fkey', 'scheduled_call', 'admin_call', ['admin_call_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('scheduled_call_call_routing_id_fkey', 'scheduled_call', 'call_routing', ['call_routing_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scheduled_call_call_routing_id_fkey', 'scheduled_call', type_='foreignkey')
    op.drop_constraint('scheduled_call_admin_call_id_fkey', 'scheduled_call', type_='foreignkey')
    op.create_foreign_key('scheduled_call_admin_call_id_fkey', 'scheduled_call', 'admin_call', ['admin_call_id'], ['id'])
    op.create_foreign_key('scheduled_call_call_routing_id_fkey', 'scheduled_call', 'call_routing', ['call_routing_id'], ['id'])
    op.drop_constraint('call_leg_call_routing_id_fkey', 'call_leg', type_='foreignkey')
    op.drop_constraint('call_leg_call_id_fkey', 'call_leg', type_='foreignkey')
    op.create_foreign_key('call_leg_call_id_fkey', 'call_leg', 'call', ['call_id'], ['id'])
    op.create_foreign_key('call_leg_call_routing_id_fkey', 'call_leg', 'call_routing', ['call_routing_id'], ['id'])
    op.drop_constraint('admin_call_call_routing_id_fkey', 'admin_call', type_='foreignkey')
    op.create_foreign_key('admin_call_call_routing_id_fkey', 'admin_call', 'call_routing', ['call_routing_id'], ['id'])
    # ### end Alembic commands ###
